### ISSUE TITLE
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by sooheon** [dmlc/dgl#2277]
## 🐛 Bug

DGL 0.5.2 built with CUDA 11 support gives following error when calling g.send_and_recv or g.pull with selected edges/nodes.

## To Reproduce

1. Install dgl 0.5.2 from source with CUDA 11
1. create graph and populate edata and ndata with some random floats
```
g.send_and_recv([1, 2, 3], fn.copy_e('e', 'e'), fn.sum('e', 'z'))

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-c3dd700abfdc>", line 1, in <module>
    g.send_and_recv([1, 2, 3], fn.copy_e('e', 'e'), fn.sum('e', 'z'))
  File "/opt/conda/lib/python3.7/site-packages/dgl-0.5.2-py3.7-linux-x86_64.egg/dgl/heterograph.py", line 4232, in send_and_recv
    ndata = core.message_passing(_create_compute_graph(g, u, v, eid),
  File "/opt/conda/lib/python3.7/site-packages/dgl-0.5.2-py3.7-linux-x86_64.egg/dgl/heterograph.py", line 5885, in _create_compute_graph
    unique_src, src_map = utils.relabel(u)
  File "/opt/conda/lib/python3.7/site-packages/dgl-0.5.2-py3.7-linux-x86_64.egg/dgl/utils/internal.py", line 748, in relabel
    unique_x = F.unique(x)
  File "/opt/conda/lib/python3.7/site-packages/dgl-0.5.2-py3.7-linux-x86_64.egg/dgl/backend/pytorch/tensor.py", line 277, in unique
    return th.unique(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/functional.py", line 767, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/opt/conda/lib/python3.7/site-packages/torch/functional.py", line 682, in _unique_impl
    return_counts=return_counts,
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal

g.update_all(fn.copy_e('e', 'e'), fn.sum('e', 'z'))

=> works fine
```

## Expected behavior

Function as it does with CUDA 10.2

## Environment

 - DGL Version (e.g., 1.0): 0.5.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.8.0 nightly
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): https://docs.dgl.ai/install/index.html#install-from-source
 - Python version: 3.7.8
 - CUDA/cuDNN version (if applicable): 11.0
 - GPU models and configuration (e.g. V100): A100
 - Any other relevant information:

**Comment by BarclayII** [comment]
I believe this is related to the issue in https://github.com/aws/deep-learning-containers/pull/639#issuecomment-706138503.  We can reproduce it reliably and it seems that the issue is in some interaction between PyTorch and CUB.

**Comment by jermainewang** [comment]
HI @sooheon, could you try the following steps and see whether the issue still exists?

1. Download and install the latest CUDA 11.1 and its corresponding driver. My driver version is 455.23.05.
1. Install the latest PyTorch 1.8.0 nightly build. My torch version is 1.8.0.dev20201016.
1. Build DGL from source (preferred on 0.5.x branch). You need to change the following lines in CMakeLists.txt:
   - Comment out L50. `include_directories("third_party/cub/")` because `cub` is now part of CUDA from 11.0 and DGL is still using an old one.
   - On L82 and L84, change `std=c++11` to `std=c++14`.
1. Rebuild.

The solution works for me on an EC2 p2.xlarge instance (K80 GPU). My OS is ubuntu 20.04.

**Comment by sooheon** [comment]
@jermainewang cmake errors for me:

Output:
```
-- Start configuring project dgl
-- Build with CUDA support
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
-- Found CUDA_CUDA_LIBRARY=/usr/local/cuda/targets/x86_64-linux/lib/stubs/libcuda.so
-- Found CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
-- Found CUDA_NVRTC_LIBRARY=/usr/local/cuda/lib64/libnvrtc.so
-- Found CUDA_CUBLAS_LIBRARY=/usr/local/cuda/lib64/libcublas.so
-- Running GPU architecture autodetection
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
-- Found CUDA arch 8.0 8.0 8.0 8.0
-- NVCC extra flags: -gencode arch=compute_80,code=sm_80 --expt-extended-lambda -Wno-deprecated-declarations
-- /home/sooheon_k_gmail_com/dgl/third_party/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "dgl" in directory /home/sooheon_k_gmail_com/dgl

-- Configuring incomplete, errors occurred!
See also "/home/sooheon_k_gmail_com/dgl/build/CMakeFiles/CMakeOutput.log".
See also "/home/sooheon_k_gmail_com/dgl/build/CMakeFiles/CMakeError.log".
```

nvidia-smi:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0    70W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-SXM4-40GB      Off  | 00000000:00:05.0 Off |                    0 |
| N/A   47C    P0    69W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  A100-SXM4-40GB      Off  | 00000000:00:06.0 Off |                    0 |
| N/A   47C    P0    67W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  A100-SXM4-40GB      Off  | 00000000:00:07.0 Off |                    0 |
| N/A   55C    P0    72W / 400W |      0MiB / 40536MiB |     19%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by sooheon** [comment]
Looks like it's a cmake version issue: https://github.com/marian-nmt/marian/issues/261

I wil try after updating cmake

**Comment by sooheon** [comment]
@jermainewang Can confirm, after getting DGL to compile with your changes the `invalid device ordinal` error does not appear.

**Comment by Smilenone** [comment]
@jermainewang  There since a cmake error for me.

```
PS C:\Users\Knotn\dgl\build> cmake -DCMAKE_CXX_FLAGS="-DDMLC_LOG_STACK_TRACE=0 -DDGL_EXPORTS" -DCMAKE_MAKE_PROGRAM=mingw32-make .. -G "MSYS Makefiles"
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: E:/Tools/Anaconda/Library/mingw-w64/bin/gcc.exe
-- Check for working C compiler: E:/Tools/Anaconda/Library/mingw-w64/bin/gcc.exe - broken
CMake Error at E:/Tools/Anaconda/Library/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "E:/Tools/Anaconda/Library/mingw-w64/bin/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Knotn/dgl/build/CMakeFiles/CMakeTmp

    Run Build Command(s):mingw32-make cmTC_9cbfa/fast && mingw32-make  -f CMakeFiles/cmTC_9cbfa.dir/build.make CMakeFiles/cmTC_9cbfa.dir/build
    mingw32-make[1]: Entering directory 'C:/Users/Knotn/dgl/build/CMakeFiles/CMakeTmp'
    CMakeFiles/cmTC_9cbfa.dir/build.make:85: recipe for target 'CMakeFiles/cmTC_9cbfa.dir/testCCompiler.c.obj' failed
    process_begin: CreateProcess(NULL, sh.exe -c "/E/Tools/Anaconda/Library/bin/cmake.exe -E cmake_echo_color --switch= --progress-dir=/C/Users/Knotn/dgl/build/CMakeFiles/CMakeTmp/CMakeFiles --progress-num=1 Building C object CMakeFiles/cmTC_9cbfa.dir/testCCompiler.c.obj", ...) failed.
    make (e=2): 系统找不到指定的文件。
    mingw32-make[1]: *** [CMakeFiles/cmTC_9cbfa.dir/testCCompiler.c.obj] Error 2
    mingw32-make[1]: Leaving directory 'C:/Users/Knotn/dgl/build/CMakeFiles/CMakeTmp'
    Makefile:141: recipe for target 'cmTC_9cbfa/fast' failed
    mingw32-make: *** [cmTC_9cbfa/fast] Error 2

```
