### ISSUE TITLE
Hanging in Distributed GNN training

### ISSUE THREAD

**Issue by xcwanAndy** [dmlc/dgl#2315]
## 🐛 Bug
Hi, I'm running a distirbuted GNN training demo on AWS, but failed and find the process hanging.

## To Reproduce
I set two machines and use the code: https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/experimental/train_dist.py

1. Run this script with `dgl/tools/launch.py`
```
python3 ~/gnn/dgl/tools/launch.py \
    --workspace ~/graphsage/ \
    --num_trainers 1 \
    --num_samplers 1 \
    --num_servers 1 \
    --part_config cora.json \
    --ip_config ip_config.txt \
    "/home/xinchen/miniconda3/envs/py37/bin/python dgl_code/train_dist.py --graph_name cora --ip_config ip_config.txt --num_servers 1 --num_epochs 30 --batch_size 1000 --num_workers 1 | tee /home/xinchen/graphsage/output.txt
```

## Expected behavior

The log is shown below:
```
All are prepared, start to train
Using backend: pytorch
Using backend: pytorch
Namespace(batch_size=1000, batch_size_eval=10000, close_profiler=False, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='cora', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=1, part_config=None, standalone=False)
Namespace(batch_size=1000, batch_size_eval=10000, close_profiler=False, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='cora', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=30, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=1, part_config=None, standalone=False)
Machine (0) client (2) connect to server successfuly!
Machine (1) client (1) connect to server successfuly!
rank: 0
rank: 1
part 1, train: 70 (local: 70), val: 250 (local: 238), test: 500 (local: 463)
part 0, train: 70 (local: 70), val: 250 (local: 250), test: 500 (local: 500)
#labels: 7
#labels: 7
/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Part 1 | Epoch 00000 | Step 00000 | Loss 2.0028 | Train Acc 0.0571 | Speed (samples/sec) nan | GPU 0.0 MiB | time 0.031 s
/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount
Part 1 | Epoch 00000 | Step 00000 | Loss 2.0028 | Train Acc 0.0571 | Speed (samples/sec) nan | GPU 0.0 MiB | time 0.031 s
/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Part 1, Epoch Time(s): 0.1003, sample+data_copy: 0.0673, forward: 0.0248, backward: 0.0037, update: 0.0020, #seeds: 70, #inputs: 785
Part 0 | Epoch 00000 | Step 00000 | Loss 1.9378 | Train Acc 0.2286 | Speed (samples/sec) nan | GPU 0.0 MiB | time 0.037 s
Part 0, Epoch Time(s): 0.1008, sample+data_copy: 0.0613, forward: 0.0262, backward: 0.0082, update: 0.0018, #seeds: 70, #inputs: 784
Part 0 | Epoch 00001 | Step 00000 | Loss 1.9284 | Train Acc 0.2286 | Speed (samples/sec) nan | GPU 0.0 MiB | time 0.033 s
Part 1 | Epoch 00001 | Step 00000 | Loss 1.9879 | Train Acc 0.0571 | Speed (samples/sec) nan | GPU 0.0 MiB | time 0.029 s
Part 1, Epoch Time(s): 0.0867, sample+data_copy: 0.0570, forward: 0.0239, backward: 0.0030, update: 0.0011, #seeds: 70, #inputs: 798
Part 0, Epoch Time(s): 0.0863, sample+data_copy: 0.0523, forward: 0.0237, backward: 0.0073, update: 0.0012, #seeds: 70, #inputs: 781
Part 0 | Epoch 00002 | Step 00000 | Loss 1.9186 | Train Acc 0.2286 | Speed (samples/sec) nan | GPU 0.0 MiB | time 0.030 s
Part 1 | Epoch 00002 | Step 00000 | Loss 1.9771 | Train Acc 0.0571 | Speed (samples/sec) nan | GPU 0.0 MiB | time 0.033 s
Part 1, Epoch Time(s): 0.0691, sample+data_copy: 0.0350, forward: 0.0241, backward: 0.0081, update: 0.0011, #seeds: 70, #inputs: 795Part 0, Epoch Time(s): 0.0688, sample+data_copy: 0.0384, forward: 0.0257, backward: 0.0028, update: 0.0011, #seeds: 70, #inputs: 799

Part 0 | Epoch 00003 | Step 00000 | Loss 1.9033 | Train Acc 0.2286 | Speed (samples/sec) 2401.8626 | GPU 0.0 MiB | time 0.029 s
Part 1 | Epoch 00003 | Step 00000 | Loss 1.9675 | Train Acc 0.0571 | Speed (samples/sec) 2167.8230 | GPU 0.0 MiB | time 0.032 sPart 0, Epoch Time(s): 0.0646, sample+data_copy: 0.0348, forward: 0.0251, backward: 0.0029, update: 0.0010, #seeds: 70, #inputs: 800

Part 1, Epoch Time(s): 0.0660, sample+data_copy: 0.0331, forward: 0.0213, backward: 0.0088, update: 0.0011, #seeds: 70, #inputs: 797
Part 0 | Epoch 00004 | Step 00000 | Loss 1.8955 | Train Acc 0.2286 | Speed (samples/sec) 2259.0683 | GPU 0.0 MiB | time 0.033 s
Part 1 | Epoch 00004 | Step 00000 | Loss 1.9576 | Train Acc 0.0571 | Speed (samples/sec) 2172.3315 | GPU 0.0 MiB | time 0.032 s
Part 0, Epoch Time(s): 0.0682, sample+data_copy: 0.0345, forward: 0.0232, backward: 0.0077, update: 0.0011, #seeds: 70, #inputs: 783Part 1, Epoch Time(s): 0.0682, sample+data_copy: 0.0355, forward: 0.0230, backward: 0.0070, update: 0.0011, #seeds: 70, #inputs: 837

|V|=2708, eval batch size: 10000
|V|=2708, eval batch size: 10000
1it [00:00, 12.14it/s]
1it [00:00,  7.94it/s]
|V|=2708, eval batch size: 10000|V|=2708, eval batch size: 10000

1it [00:00, 18.02it/s]
Machine (1) client (0) connect to server successfuly!
Using backend: pytorc
```

And then it hangs and does not release its CPU resources.
## Environment

 - DGL Version (e.g., 1.0): 0.5.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.6.0 (CPU only)
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): /
 - Python version: python 3.7.0
 - CUDA/cuDNN version (if applicable): /
 - GPU models and configuration (e.g. V100): /
 - Any other relevant information:

## Additional context
I suggest it might because of no output: `Machine (0) client (3) connect to server successfuly!`.
I have two questions:
- Is this exactly why the program hangs?
- In `launch.py`, the tot_num_client = `args.num_trainers * (1 + args.num_samplers) * len(hosts)`. Would you please tell me why **+1**?

**Comment by xcwanAndy** [comment]
I just find out that if I delete the evaluation block:
```
        if epoch % args.eval_every == 0 and epoch != 0:
            start = time.time()
            val_acc, test_acc = evaluate(model.module, g, g.ndata['features'],
                                         g.ndata['labels'], val_nid, test_nid, args.batch_size_eval, device)
            print('Part {}, Val Acc {:.4f}, Test Acc {:.4f}, time: {:.4f}'.format(g.rank(), val_acc, test_acc,
                                                                                  time.time() - start))
```
The training process would successfully run and finish.

Do anyone have any suggestions about it?

**Comment by aksnzhy** [comment]
@xcwanAndy It seems that the evaluation process has node and edge that never have never seen in the training process. What dataset you use? Can you try the ogb-product successfully in your setting?

**Comment by aksnzhy** [comment]
@xcwanAndy It seems that you are out of memory on the evaluation because we use full batch inference here.

**Comment by xcwanAndy** [comment]
@aksnzhy Just check the program and verify that the memory is enough for evaluation.
And I think the issue lies in the communication part. As I put the initialization of dgl.distributed-related code from `DistSAGE.inference` into `run`, the program can successfully run and finish.

Besides, I find that after finishing the program, immediately if I try to rerun it, I always get:
```
Traceback (most recent call last):
  File "dgl_code/train_dist.py", line 356, in <module>
    main(args)
  File "dgl_code/train_dist.py", line 289, in main
    dgl.distributed.initialize(args.ip_config, args.num_servers, num_workers=args.num_workers)
  File "/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/distributed/dist_context.py", line 101, in initialize
    serv.start()
  File "/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/distributed/dist_graph.py", line 297, in start
    num_clients=self.num_clients, server_state=server_state)
  File "/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/distributed/rpc_server.py", line 68, in start_server
    rpc.receiver_wait(ip_addr, port, num_clients)
  File "/home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/distributed/rpc.py", line 152, in receiver_wait
    _CAPI_DGLRPCReceiverWait(ip_addr, int(port), int(num_senders))
  File "dgl/_ffi/_cython/./function.pxi", line 287, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 222, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 211, in dgl._ffi._cy3.core.FuncCall3
  File "dgl/_ffi/_cython/./base.pxi", line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [08:58:27] /opt/dgl/src/rpc/network/socket_communicator.cc:197: Cannot bind to 192.168.1.203:30050
Stack trace:
  [bt] (0) /home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7ff9dd7c4a4f]
  [bt] (1) /home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/libdgl.so(dgl::network::SocketReceiver::Wait(char const*, int)+0x4bf) [0x7ff9ddfa01ff]
  [bt] (2) /home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/libdgl.so(+0xfaa39e) [0x7ff9ddfa539e]
  [bt] (3) /home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7ff9dde59f88]
  [bt] (4) /home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0x17643) [0x7ff9db9b4643]
  [bt] (5) /home/xinchen/miniconda3/envs/py37/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0x1796b) [0x7ff9db9b496b]
  [bt] (6) /home/xinchen/miniconda3/envs/py37/bin/python(_PyObject_FastCallKeywords+0x4ab) [0x564990d3861b]
  [bt] (7) /home/xinchen/miniconda3/envs/py37/bin/python(_PyEval_EvalFrameDefault+0x4bc6) [0x564990d93f56]
  [bt] (8) /home/xinchen/miniconda3/envs/py37/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x564990d3707b]
```

which seems that some communication resources aren't completely released immediately, but several minutes later the program can work.

Do you have any suggestions about it?

**Comment by aksnzhy** [comment]
This problem happends because the last server process is not killed. You can kill the backend process or restart your machine and re-try it.

**Comment by zheng-da** [comment]
For the second problem, it's because the processes you run previously weren't killed completely. You should kill them and try again.

**Comment by zheng-da** [comment]
For the first problem, I found the same issue when I upgrade my Ubuntu. I think there is a bug in `DistDataloader`, which is caused by the different behavior of the process pool in different versions of Python.

To verify if this is the problem, please set the number of sampler workers to 0. it works for me.

**Comment by fanfanman** [comment]
@zheng-da Thanks a lot for your suggestion. Setting `--num_workers 0` works for me. The training process can successfully run and finish with this parameter setting.

---
Just trying to provide some info about the aforementioned bug on my side, by running 
``` python
python3 launch.py \
--workspace /home/notebook/code/personal/distributed-training \
--num_trainers 1 \
--num_samplers 4 \
--num_servers 1 \
--part_config data/reddit.json \
--ip_config ip_config.txt \
"python3 train_dist.py --graph_name reddit --ip_config ip_config.txt --num_servers 1 --num_epochs 21 --batch_size 1000 --num_workers 4 --batch_size_eval 10000 --eval_every 21"
```
the log goes with
```
...
Part 3 | Epoch 00019 | Step 00000 | Loss 0.2396 | Train Acc 0.9400 | Speed (samples/sec) 633.4192 | GPU 0.0 MB | time 3.965 s
Part 0 | Epoch 00019 | Step 00000 | Loss 0.5537 | Train Acc 0.8860 | Speed (samples/sec) 629.8864 | GPU 0.0 MB | time 3.856 s
Part 2 | Epoch 00019 | Step 00000 | Loss 0.3161 | Train Acc 0.9410 | Speed (samples/sec) 637.4220 | GPU 0.0 MB | time 3.728 s
Part 1 | Epoch 00019 | Step 00000 | Loss 0.3975 | Train Acc 0.8900 | Speed (samples/sec) 647.6771 | GPU 0.0 MB | time 3.695 s
Part 0 | Epoch 00019 | Step 00020 | Loss 0.5659 | Train Acc 0.8760 | Speed (samples/sec) 625.9735 | GPU 0.0 MB | time 47.315 s
Part 3 | Epoch 00019 | Step 00020 | Loss 0.2882 | Train Acc 0.9380 | Speed (samples/sec) 629.3883 | GPU 0.0 MB | time 47.271 s
Part 1 | Epoch 00019 | Step 00020 | Loss 0.5021 | Train Acc 0.8940 | Speed (samples/sec) 643.8682 | GPU 0.0 MB | time 46.047 s
Part 2 | Epoch 00019 | Step 00020 | Loss 0.2852 | Train Acc 0.9370 | Speed (samples/sec) 633.3737 | GPU 0.0 MB | time 47.089 s
Part 3, Epoch Time(s): 79.1984, sample+data_copy: 1.4319, forward: 34.7500, backward: 41.6808, update: 0.1272, #seeds: 38357, #inputs: 2651849
Part 2, Epoch Time(s): 79.1982, sample+data_copy: 2.0034, forward: 47.5407, backward: 27.8843, update: 0.3124, #seeds: 38358, #inputs: 2925943
Part 1, Epoch Time(s): 79.1983, sample+data_copy: 3.3168, forward: 53.2103, backward: 20.1117, update: 0.1264, #seeds: 38358, #inputs: 2739876
Part 0, Epoch Time(s): 79.1990, sample+data_copy: 1.6041, forward: 33.3992, backward: 42.8057, update: 0.0344, #seeds: 38358, #inputs: 2606276
Part 0 | Epoch 00020 | Step 00000 | Loss 0.5861 | Train Acc 0.8620 | Speed (samples/sec) 629.2731 | GPU 0.0 MB | time 6.116 s
Part 3 | Epoch 00020 | Step 00000 | Loss 0.2777 | Train Acc 0.9360 | Speed (samples/sec) 632.2422 | GPU 0.0 MB | time 6.240 s
Part 2 | Epoch 00020 | Step 00000 | Loss 0.3240 | Train Acc 0.9320 | Speed (samples/sec) 636.3954 | GPU 0.0 MB | time 6.021 s
Part 1 | Epoch 00020 | Step 00000 | Loss 0.5347 | Train Acc 0.8630 | Speed (samples/sec) 646.5480 | GPU 0.0 MB | time 5.936 s
Part 3 | Epoch 00020 | Step 00020 | Loss 0.2586 | Train Acc 0.9420 | Speed (samples/sec) 628.0669 | GPU 0.0 MB | time 47.969 s
Part 1 | Epoch 00020 | Step 00020 | Loss 0.4590 | Train Acc 0.8800 | Speed (samples/sec) 642.1625 | GPU 0.0 MB | time 47.292 s
Part 0 | Epoch 00020 | Step 00020 | Loss 0.4884 | Train Acc 0.8850 | Speed (samples/sec) 625.1585 | GPU 0.0 MB | time 48.123 s
Part 2 | Epoch 00020 | Step 00020 | Loss 0.2510 | Train Acc 0.9340 | Speed (samples/sec) 632.2729 | GPU 0.0 MB | time 47.565 s
Part 1, Epoch Time(s): 78.5027, sample+data_copy: 2.7985, forward: 51.7272, backward: 21.9855, update: 0.1297, #seeds: 38358, #inputs: 2740081
Part 0, Epoch Time(s): 78.5025, sample+data_copy: 1.5319, forward: 27.8280, backward: 47.7950, update: 0.0343, #seeds: 38358, #inputs: 2605981
Part 3, Epoch Time(s): 78.5033, sample+data_copy: 1.6624, forward: 29.0036, backward: 46.5472, update: 0.0333, #seeds: 38357, #inputs: 2649218
Part 2, Epoch Time(s): 78.5076, sample+data_copy: 2.2716, forward: 48.8991, backward: 25.4082, update: 0.1272, #seeds: 38358, #inputs: 2923411
|V|=232965, eval batch size: 10000
|V|=232965, eval batch size: 10000
|V|=232965, eval batch size: 10000
|V|=232965, eval batch size: 10000
6it [00:18,  3.01s/it]
6it [00:18,  3.16s/it]
6it [00:23,  3.87s/it]
6it [00:23,  3.89s/it]
|V|=232965, eval batch size: 10000
|V|=232965, eval batch size: 10000
|V|=232965, eval batch size: 10000
|V|=232965, eval batch size: 10000
6it [00:08,  1.39s/it]
6it [00:08,  1.46s/it]
6it [00:09,  1.58s/it]
6it [00:10,  1.70s/it]
Part 0, Val Acc 0.9293, Test Acc 0.9265, time: 34.5077
Part 3, Val Acc 0.9663, Test Acc 0.9657, time: 34.6522
parent ends
parent ends
Part 1, Val Acc 0.9344, Test Acc 0.9271, time: 34.9955
Part 2, Val Acc 0.9728, Test Acc 0.9733, time: 34.9909
parent ends
parent ends
Using backend: pytorch
/home/ogp/.local/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py:256: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
Namespace(batch_size=1000, batch_size_eval=10000, close_profiler=False, dataset=None, dropout=0.5, eval_every=21, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=None, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=21, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=4, part_config=None, standalone=False)
load reddit
start graph service on server 0 for part 0
Wait connections ...
20 clients connected!
Server (0) shutdown.
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:val_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:features-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:label-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:test_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:train_mask-kvdata- for shared memory
Using backend: pytorch
/home/ogp/.local/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py:256: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:labels-kvdata- for shared memory
Namespace(batch_size=1000, batch_size_eval=10000, close_profiler=False, dataset=None, dropout=0.5, eval_every=21, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=None, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=21, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=4, part_config=None, standalone=False)
load reddit
start graph service on server 3 for part 3
Wait connections ...
20 clients connected!
Server (3) shutdown.
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:feat-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h_last-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:val_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove reddit for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:features-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:label-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:test_mask-kvdata- for shared memory
[[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_data for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:train_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:labels-kvdata- for shared memory
03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indices for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:feat-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indptr for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h_last-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:: remove /reddit_node_inner_node for shared memory
36: remove reddit for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node__ID for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_data for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indices for shared memory
36: remove /reddit_edge_inner_edge for shared memory
[[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indptr for shared memory
03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge__ID for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_edge_map for shared memory
: remove /reddit_node_inner_node for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_node_map for shared memory[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove 
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: /reddit_node__ID for shared memory
[remove /reddit_node_meta for shared memory
03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_inner_edge for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge__ID for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_edge_map for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_node_map for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_meta for shared memory
Namespace(batch_size=1000, batch_size_eval=10000, close_profiler=False, dataset=None, dropout=0.5, eval_every=21, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=None, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=21, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=4, part_config=None, standalone=False)
load reddit
start graph service on server 1 for part 1
Wait connections ...
20 clients connected!
Server (1) shutdown.
Using backend: pytorch
/home/ogp/.local/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py:256: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:val_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:features-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:label-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:test_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:train_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:labels-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:feat-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h_last-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove reddit for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_data for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indices for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indptr for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_inner_node for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node__ID for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_inner_edge for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge__ID for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_edge_map for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_node_map for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_meta for shared memory
Namespace(batch_size=1000, batch_size_eval=10000, close_profiler=False, dataset=None, dropout=0.5, eval_every=21, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=None, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=21, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=4, part_config=None, standalone=False)
load reddit
start graph service on server 2 for part 2
Wait connections ...
20 clients connected!
Server (2) shutdown.
Using backend: pytorch
/home/ogp/.local/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py:256: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:val_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:features-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:label-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:test_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:train_mask-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:labels-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:feat-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:h_last-kvdata- for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove reddit for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_data for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indices for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indptr for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_inner_node for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node__ID for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_inner_edge for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge__ID for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_edge_map for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_node_map for shared memory
[03:02:26] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_meta for shared memory
Machine (0) client (3) connect to server successfuly!
Machine (0) client (1) connect to server successfuly!
Using backend: pytorch
Using backend: pytorch
Machine (0) client (2) connect to server successfuly!
Using backend: pytorch
Machine (3) client (9) connect to server successfuly!
Machine (3) client (5) connect to server successfuly!
Using backend: pytorch
Using backend: pytorch
Machine (0) client (0) connect to server successfuly!
Using backend: pytorch
Machine (3) client (6) connect to server successfuly!
Using backend: pytorch
Machine (3) client (8) connect to server successfuly!
Using backend: pytorch
Machine (2) client (17) connect to server successfuly!
Using backend: pytorch
Machine (2) client (15) connect to server successfuly!
Machine (2) client (18) connect to server successfuly!
Using backend: pytorch
Using backend: pytorch
Machine (2) client (19) connect to server successfuly!
Using backend: pytorch
Machine (1) client (11) connect to server successfuly!
Using backend: pytorch
Machine (1) client (10) connect to server successfuly!
Using backend: pytorch
Machine (1) client (12) connect to server successfuly!
Using backend: pytorch
Machine (1) client (13) connect to server successfuly!
Using backend: pytorch
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7fbb7b8d8da0>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7fbb7b8dd7f0>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7f24c65e0128>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7f24c65e0cf8>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7f20b079ca90>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7f20b079e7b8>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7fd8af69c7f0>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <bound method DistDataLoader.__del__ of <dgl.distributed.dist_dataloader.DistDataLoader object at 0x7fd8af689550>>
Traceback (most recent call last):
  File "/home/ogp/.local/lib/python3.6/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 355, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
```

**Comment by zheng-da** [comment]
it seems there are still some problems with process pool. we'll try to fix it.

**Comment by LouisYZK** [comment]
> I just find out that if I delete the evaluation block:
> 
> ```
>         if epoch % args.eval_every == 0 and epoch != 0:
>             start = time.time()
>             val_acc, test_acc = evaluate(model.module, g, g.ndata['features'],
>                                          g.ndata['labels'], val_nid, test_nid, args.batch_size_eval, device)
>             print('Part {}, Val Acc {:.4f}, Test Acc {:.4f}, time: {:.4f}'.format(g.rank(), val_acc, test_acc,
>                                                                                   time.time() - start))
> ```
> 
> The training process would successfully run and finish.
> 
> Do anyone have any suggestions about it?

I have the same problem stub at evaluation, it seems eval data can't load success.

**Comment by zheng-da** [comment]
if you are using python 3.8, could you run distributed training with 0 sampler for now?

**Comment by LouisYZK** [comment]
> if you are using python 3.8, could you run distributed training with 0 sampler for now?

I'm using python3.7.  I found that  eval process result on each machine's has been seen in log, however the whole distribute process hang after the first evaluation.

**Comment by zheng-da** [comment]
setting the number of samplers to 0 helps?

**Comment by LouisYZK** [comment]
> setting the number of samplers to 0 helps?

Ah.... it works when sample_num=0....; But could you tell me the reason? And if it is 0, what is the default sample process number?
Thanks a lot !!

**Comment by zheng-da** [comment]
@LouisYZK we fixed the issue in the master branch. could you give it a try and see if it works for you now?

**Comment by jermainewang** [comment]
Closed due to inactivity. Please try the latest DGL.
