### ISSUE TITLE
A RuntimeError when dgl.batch is applied on heterographs?

### ISSUE THREAD

**Issue by sakuraiiiii** [dmlc/dgl#2640]
Hi, I have a question w.r.t. ```dgl.batch``` on heterographs. When the following code is running on cuda:
```python
import torch
from torch import nn
import dgl
import dgl.nn.pytorch as dglnn

device = torch.device('cuda')

hg1 = dgl.heterograph({('A', 'AB', 'B'): (torch.tensor([0, 1, 1]), torch.tensor([0, 1, 2])), 
                       ('A', 'AA', 'A'): (torch.tensor([0, 1]), torch.tensor([1, 0])), 
                       ('B', 'BB', 'B'): ([], []), 
                       ('A', 'AC', 'C'): ([], []), 
                       ('B', 'BC', 'C'): ([], []), 
                       ('C', 'CC', 'C'): ([], [])}, 
                      num_nodes_dict={'A': 2, 'B': 3, 'C': 0})

hg1.nodes['A'].data['t'] = torch.randn(2, 5)
hg1.nodes['B'].data['t'] = torch.randn(3, 5)
hg1.nodes['C'].data['t'] = torch.tensor([]).float()

hg2 = dgl.heterograph({('A', 'AC', 'C'): (torch.tensor([0, 1, 1]), torch.tensor([0, 1, 2])), 
                       ('A', 'AA', 'A'): (torch.tensor([0, 1]), torch.tensor([1, 0])), 
                       ('B', 'BB', 'B'): ([], []), 
                       ('C', 'CC', 'C'): ([], []), 
                       ('A', 'AB', 'B'): ([], []), 
                       ('B', 'BC', 'C'): ([], [])}, num_nodes_dict={'A': 2, 'B': 0, 'C': 3})

hg2.nodes['A'].data['t'] = torch.randn(2, 5)
hg2.nodes['C'].data['t'] = torch.randn(3, 5)
hg2.nodes['B'].data['t'] = torch.tensor([]).float()

hgs_list = [hg1, hg2]

hgs = dgl.batch(hgs_list)

class ModelLayer(nn.Module):
    def __init__(self, in_feats, out_feats):
        super(ModelLayer, self).__init__()
        mods = {'AA': dglnn.GraphConv(in_feats, out_feats), 
                'AB': dglnn.GraphConv(in_feats, out_feats), 
                'BB': dglnn.GraphConv(in_feats, out_feats), 
                'AC': dglnn.GraphConv(in_feats, out_feats), 
                'BC': dglnn.GraphConv(in_feats, out_feats), 
                'CC': dglnn.GraphConv(in_feats, out_feats)}
            
        self.heterogcn = dglnn.HeteroGraphConv(mods)
        
    def forward(self, g, x):
        h_v = self.heterogcn(g, x)
        return h_v
        
        
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.hgcn1 = ModelLayer(5, 20)
        self.hgcn2 = ModelLayer(20, 1)
        
    def forward(self, g, x):
        hv = self.hgcn1(g, x)
        hv = self.hgcn2(g, hv)
        
        for ntype in hv.keys():
            g.nodes[ntype].data['h'] = hv[ntype]

        h_pred = [dgl.readout_nodes(g, 'h', ntype=ntype) for ntype in hv.keys()]
        return torch.sum(torch.stack(h_pred), dim=0)


device = torch.device('cpu')

model = Model().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=3e-4)
criterion = nn.MSELoss()

model.train()
optimizer.zero_grad()

hgs, y = hgs.to(device), torch.randn(2).to(device)

v = {}
for nty in hgs.ntypes:
    if 't' in hgs.nodes[nty].data.keys():
        v[nty] = hgs.nodes[nty].data['t']
    else:
        v[nty] = torch.tensor([]).float().to(device)
        
pred = model(g=hgs, x=v)

loss_ = criterion(y.unsqueeze(-1), pred)
loss_.backward()
optimizer.step()
print(loss_.item())
```
The following error will be returned:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-c535574719a3> in <module>
     23 
     24 loss_ = criterion(y.unsqueeze(-1), pred)
---> 25 loss_.backward()
     26 optimizer.step()
     27 print(loss_.item())

~/anaconda3/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    219                 retain_graph=retain_graph,
    220                 create_graph=create_graph)
--> 221         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    222 
    223     def register_hook(self, hook):

~/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    130     Variable._execution_engine.run_backward(
    131         tensors, grad_tensors_, retain_graph, create_graph,
--> 132         allow_unreachable=True)  # allow_unreachable flag
    133 
    134 

~/anaconda3/lib/python3.7/site-packages/torch/autograd/function.py in apply(self, *args)
     87     def apply(self, *args):
     88         # _forward_cls is defined by derived class
---> 89         return self._forward_cls.backward(self, *args)  # type: ignore
     90 
     91 

~/anaconda3/lib/python3.7/site-packages/dgl/backend/pytorch/sparse.py in backward(ctx, dy)
    244         op = ctx.backward_cache
    245         arg, offsets = ctx.saved_tensors
--> 246         m = offsets[-1].item()
    247         if op == 'sum':
    248             offsets = offsets[1:-1]

RuntimeError: CUDA error: device-side assert triggered
```
Following the solution I found on Stackoverflow, I run the command ```CUDA_LAUNCH_BLOCKING=1 python xxx.py```, then the detailed error will be returned as follows:
```python
Using backend: pytorch
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "test.py", line 116, in <module>
    loss_.backward()
  File "~/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "~/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "~/anaconda3/lib/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "~/anaconda3/lib/python3.7/site-packages/dgl/backend/pytorch/sparse.py", line 251, in backward
    indices.scatter_add_(0, offsets, th.ones_like(offsets))
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:13:56] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:103: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: device-side assert triggered
Stack trace:
  [bt] (0) ~/anaconda3/lib/python3.7/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f78113a05af]
  [bt] (1) ~/anaconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)+0x15c) [0x7f7811bbec3c]
  [bt] (2) ~/anaconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Internal::DefaultDeleter(dgl::runtime::NDArray::Container*)+0x1ad) [0x7f7811a807bd]
  [bt] (3) ~/anaconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::COO::~COO()+0xf7) [0x7f7811b99677]
  [bt] (4) ~/anaconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::~UnitGraph()+0x1ba) [0x7f7811b9943a]
  [bt] (5) ~/anaconda3/lib/python3.7/site-packages/dgl/libdgl.so(dgl::HeteroGraph::~HeteroGraph()+0x119) [0x7f7811a98559]
  [bt] (6) ~/anaconda3/lib/python3.7/site-packages/dgl/libdgl.so(DGLObjectFree+0xb5) [0x7f7811a577f5]
  [bt] (7) ~/anaconda3/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0xf1ed) [0x7f7803d6d1ed]
  [bt] (8) python(+0x1a184f) [0x5561fea5284f]


已放弃 (核心已转储)
```
When the above code is running on cpu, it will return
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-d52524aa5e94> in <module>
     23 
     24 loss_ = criterion(y.unsqueeze(-1), pred)
---> 25 loss_.backward()
     26 optimizer.step()
     27 print(loss_.item())

~/anaconda3/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    219                 retain_graph=retain_graph,
    220                 create_graph=create_graph)
--> 221         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    222 
    223     def register_hook(self, hook):

~/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    130     Variable._execution_engine.run_backward(
    131         tensors, grad_tensors_, retain_graph, create_graph,
--> 132         allow_unreachable=True)  # allow_unreachable flag
    133 
    134 

~/anaconda3/lib/python3.7/site-packages/torch/autograd/function.py in apply(self, *args)
     87     def apply(self, *args):
     88         # _forward_cls is defined by derived class
---> 89         return self._forward_cls.backward(self, *args)  # type: ignore
     90 
     91 

~/anaconda3/lib/python3.7/site-packages/dgl/backend/pytorch/sparse.py in backward(ctx, dy)
    249             indices = th.zeros(
    250                 (m,), device=offsets.device, dtype=offsets.dtype)
--> 251             indices.scatter_add_(0, offsets, th.ones_like(offsets))
    252             indices = th.cumsum(indices, -1)
    253             dx = dy[indices]

RuntimeError: index 3 is out of bounds for dimension 0 with size 3
```
It seems functions util forward propagating but return an error when it is under back propagating. However another code is running with no blank nodes without any error:
```python
hg1 = dgl.heterograph({('A', 'AB', 'B'): (torch.tensor([0, 1, 1]), torch.tensor([0, 1, 2])), 
                       ('A', 'AA', 'A'): (torch.tensor([0, 1]), torch.tensor([1, 0]))}, 
                      num_nodes_dict={'A': 2, 'B': 3})

hg1.nodes['A'].data['t'] = torch.randn(2, 5)
hg1.nodes['B'].data['t'] = torch.randn(3, 5)

hg2 = dgl.heterograph({('A', 'AA', 'A'): (torch.tensor([0, 1, 1]), torch.tensor([0, 1, 2])), 
                       ('A', 'AB', 'B'): (torch.tensor([0, 1]), torch.tensor([1, 0]))}, 
                      num_nodes_dict={'A': 3, 'B': 2})

hg2.nodes['A'].data['t'] = torch.randn(3, 5)
hg2.nodes['B'].data['t'] = torch.randn(2, 5)

hgs_list = [hg1, hg2]

hgs = dgl.batch(hgs_list)
```
Thus I think the error above appears when batch heterographs with blank nodes. How to solve this problem? Thank you.

**Comment by mufeili** [comment]
It looks like the issue is addressed in PR #2610 , can you try the nightly-built version or installing from source?

**Comment by lxyeternal** [comment]
I have the same problem, how can I solve it? Thank you.

**Comment by sakuraiiiii** [comment]
I updated `DGL`, then the problem was solved.

**Comment by lxyeternal** [comment]
> I updated `DGL`, then the problem was solved.

I have successfully solved this problem, Thank you.
