### ISSUE TITLE
The simultaneous existence of " ops.edge_softmax" and " dgl.remove_edges" results in "CUDA out of memory" after several epochs.

### ISSUE THREAD

**Issue by FANTASTPATR** [dmlc/dgl#3044]
## 🐛 Bug

The simultaneous existence of " ops.edge_softmax" and " dgl.remove_edges" results in "CUDA out of memory" after several epochs.
## To Reproduce

1.Constructing a complete graph and remove part of edges according to edge weights by threshold.
2.Performing GATConv.
3.After several epochs (3 epochs and 305 iterations in my experiment) , the error of "CUDA out of memory" will be happened suddenly.

Graph Learner:
  class Graph_Learner(nn.Module):
      def __init__(self, args, graph_structure):
          super(Graph_Learner, self).__init__()
          self.args = args
          self.graph_structure = graph_structure
          self.E1 = nn.Parameter(torch.FloatTensor(size=(self.args.GL_head, self.args.num_node, self.args.GL_dim)),
                                 requires_grad=True)
          self.E2 = nn.Parameter(torch.FloatTensor(size=(self.args.GL_head, self.args.num_node, self.args.GL_dim)),
                                 requires_grad=True)
          self.k = int(self.args.retain_ratio * self.args.num_node * self.args.num_node * self.args.batch_size)  # 保留的边条数
          # self.eye = torch.eye(self.args.num_node).to(self.args.device)
          self._reset_parameters()

    def forward(self, x):
        # graph = copy.deepcopy(self.graph_structure)
        # adj_mx = F.relu(torch.matmul(self.E1, self.E2.transpose(0, 1)))
        # graph = dgl.graph(self.graph_structure.edges())
        adj_mx = F.relu(self.E1 @ self.E2.transpose(-1, 1))
        adj_mx = F.sigmoid(adj_mx)
        adj_mx = torch.mean(adj_mx, dim=0)
        # adj_mx = adj_mx + self.eye
        edges_w = adj_mx.view(self.args.num_node * self.args.num_node).repeat(self.args.batch_size)
        k = torch.topk(edges_w, self.k)[0].min()
        mask = edges_w < k
        # graph.remove_edges(mask.nonzero().squeeze())
        graph = dgl.remove_edges(self.graph_structure, mask.nonzero().squeeze())
        graph.edata['w'] = edges_w[~mask]
        return graph
GATConv:
graph.srcdata.update({'ft': feat_src, 'el': el})
            graph.dstdata.update({'er': er})

            graph.apply_edges(fn.u_add_v(lhs_field='el', rhs_field='er', out='e'))
            e = self.leaky_relu(graph.edata.pop('e'))  # ------

            w = graph.edata['w'].unsqueeze(-1).unsqueeze(-1)
            w = torch.repeat_interleave(w, self.num_heads, 1)  # ------

            e = w * e  # -------
            # graph.edata['a'] = self.attn_drop(ops.edge_softmax(graph, e))  # -------
            graph.edata['a'] = self.attn_drop(e)

            graph.update_all(fn.u_mul_e(lhs_field='ft', rhs_field='a', out='m'), fn.sum(msg='m', out='ft'))
            rst = graph.dstdata['ft']

            if self.activation:
                rst = self.activation(rst)

        return rst

## Environment

 - DGL Version (e.g., 0.5.3):
 - Backend Library & Version (e.g., PyTorch 1.7.1+cu92):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`):
 - Build command you used (if compiling from source):
 - Python version:3.8.5
 - CUDA/cuDNN version (9.2):
 - GPU models and configuration (1080 Ti):
 - Any other relevant information:

## Additional context

Update:
I tried the source code again, OOM is NOT found this time for part of datasets, while OOM is still happened on other datasets.

Updata:
By adding torch.cuda.empty_cache() after each iteration, the problem can be solved.

**Comment by VoVAllen** [comment]
Tried the script below, didn't trigger the same problem
```python
from dgl.data import CitationGraphDataset
import torch as th
import dgl

from pynvml.smi import nvidia_smi
nvsmi = nvidia_smi.getInstance()


ds = CitationGraphDataset("cora")
g = ds[0]
g = g.to("cuda")

for i in range(100):
    print(nvsmi.DeviceQuery('memory.free, memory.total')['gpu'][0])
    g.edata['e'] = th.randn((g.num_edges(), 1), device="cuda")
    ee = dgl.ops.edge_softmax(g, g.edata['e'])
    g.remove_edges(th.arange(10, device="cuda"))
```

**Comment by VoVAllen** [comment]
The issue is resolved by `torch.cuda.empty_cache()`
