### ISSUE TITLE
Farthest Point Sampling Causes Crashes on Multiple Devices

### ISSUE THREAD

**Issue by eliphatfs** [dmlc/dgl#3340]
## To Reproduce
```python
import dgl
import dgl.geometry
import torch.utils.data as tud
import dgl.dataloading as dd
import torch
import tqdm

class D(tud.Dataset):
    def __getitem__(self, index):
        with torch.no_grad():
            tc = torch.randn(1, 1024, 3, device='cuda:0')
            dgl.geometry.farthest_point_sampler(tc, 100)
            return dgl.rand_graph(100, 200)

    def __len__(self):
        return 1024


if __name__ == "__main__":
    dev = torch.device('cuda:1')
    for b in tqdm.tqdm(dd.GraphDataLoader(D(), batch_size=32, shuffle=True)):
        b.to(dev)
```

1. Get a server with multiple CUDA cards.
2. Run the code.
3. See the crash at the second batch.

Program output:
```plain
Using backend: pytorch
  3%|███▊                                                                                                                     | 1/32 [00:07<03:52,  7.50s/it]
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    b.to(dev)
  File "/home/**/.local/lib/python3.8/site-packages/dgl/heterograph.py", line 5414, in to
    new_bnn = {k : F.copy_to(num, device, **kwargs)
  File "/home/**/.local/lib/python3.8/site-packages/dgl/heterograph.py", line 5414, in <dictcomp>
    new_bnn = {k : F.copy_to(num, device, **kwargs)
  File "/home/**/.local/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py", line 119, in copy_to
    return input.cuda(**kwargs)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'dmlc::Error'
  what():  [23:37:52] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:103: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: an illegal memory access was encountered
Stack trace:
  [bt] (0) /home/**/.local/lib/python3.8/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f09816d984f]
  [bt] (1) /home/**/.local/lib/python3.8/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)+0x15c) [0x7f0981ff60fc]
  [bt] (2) /home/**/.local/lib/python3.8/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Internal::DefaultDeleter(dgl::runtime::NDArray::Container*)+0x1ad) [0x7f0981e8b59d]
  [bt] (3) /home/**/.local/lib/python3.8/site-packages/dgl/libdgl.so(dgl::UnitGraph::COO::~COO()+0x127) [0x7f0981fd0547]
  [bt] (4) /home/**/.local/lib/python3.8/site-packages/dgl/libdgl.so(dgl::UnitGraph::~UnitGraph()+0x1ba) [0x7f0981fd01aa]
  [bt] (5) /home/**/.local/lib/python3.8/site-packages/dgl/libdgl.so(dgl::HeteroGraph::~HeteroGraph()+0x119) [0x7f0981ea6349]
  [bt] (6) /home/**/.local/lib/python3.8/site-packages/dgl/libdgl.so(DGLObjectFree+0xb5) [0x7f0981e62365]
  [bt] (7) /home/**/.local/lib/python3.8/site-packages/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so(+0x12089) [0x7f0961384089]
  [bt] (8) python3() [0x5a686c]


Aborted (core dumped)
```
(User name removed)

## Expected behavior

Everything working correctly.

## Environment

 - DGL Version (e.g., 1.0): 0.7.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8.10
 - CUDA/cuDNN version (if applicable): 11.4
 - GPU models and configuration (e.g. V100): 4xV100
 - Any other relevant information:

**Comment by eliphatfs** [comment]
Seems same root cause with #3318. Still keeping open for another check.

**Comment by hetong007** [comment]
Thanks for reporting. Could you please try to test with https://github.com/dmlc/dgl/pull/3327 ?

If compling DGL is not convenient, you could also wait to install the nightly-build tomorrow via commands from here: https://www.dgl.ai/pages/start.html

**Comment by eliphatfs** [comment]
Tested with nightly build `dgl-cu110`, version `0.8a210911`. It no longer crashes.

**Comment by hetong007** [comment]
Thanks for the feedback. We see this issue fixed then.
