### ISSUE TITLE
`adj_product_graph` crashes with large number of edges.

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#3444]
## 🐛 Bug

The following code crashes:
```python
import dgl
import torch
C = dgl.graph((torch.randint(0, 9000, (10000000,)), torch.randint(0, 9000, (10000000,))), num_nodes=9000)
C = dgl.to_simple(C)
C = C.to('cuda')
C.edata['w'] = torch.randn(C.num_edges()).cuda()
dgl.adj_product_graph(C, C, 'w')
```

Traceback looks like this, suggesting that the error is `CUSPARSE_STATUS_INSUFFICIENT_RESOURCES` thrown at the second `cusparseSpGEMM_workEstimation` call in https://github.com/dmlc/dgl/blob/579cd3eb49a43717072627440afc1b66f3938adc/src/array/cuda/csr_mm.cu#L87.  However I checked that the workspace allocated is around 100M which should be manageable.  Not sure what is the problem.

```
Traceback (most recent call last):
  File "a.py", line 18, in <module>
    dgl.adj_product_graph(C, C, 'w')
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/transform.py", line 2641, in adj_product_graph
    C_gidx, C_weights = F.csrmm(
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/backend/pytorch/sparse.py", line 647, in csrmm
    CSRMM.apply(gidxA, A_weights, gidxB, B_weights, num_vtypes)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/backend/pytorch/sparse.py", line 534, in forward
    gidxC, C_weights = _csrmm(gidxA, A_weights, gidxB, B_weights, num_vtypes)
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/sparse.py", line 540, in _csrmm
    C, C_weights = _CAPI_DGLCSRMM(
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/_ffi/_ctypes/function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/_ffi/base.py", line 64, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [09:32:57] /mnt/b/gq/dgl/src/array/cuda/csr_mm.cu:89: Check failed: e == CUSPARSE_STATUS_SUCCESS: CUSPARSE ERROR: 11
Stack trace:
  [bt] (0) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(+0x662992) [0x7f4fd7976992]
  [bt] (1) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(std::pair<dgl::aten::CSRMatrix, dgl::runtime::NDArray> dgl::aten::cusparse::CusparseSpgemm<float, int>(dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray)+0x725) [0x7f4fd79773a5]
  [bt] (2) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(std::pair<dgl::aten::CSRMatrix, dgl::runtime::NDArray> dgl::aten::CSRMM<2, long, float>(dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::aten::CSRMatrix
const&, dgl::runtime::NDArray)+0xa44) [0x7f4fd797a2f4]
  [bt] (3) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::aten::CSRMM(dgl::aten::CSRMatrix, dgl::runtime::NDArray, dgl::aten::CSRMatrix, dgl::runtime::NDArray)+0x1197) [0x7f4fd7762cd7]
  [bt] (4) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(+0x45941b) [0x7f4fd776d41b]
  [bt] (5) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(+0x459c24) [0x7f4fd776dc24]
  [bt] (6) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(DGLFuncCall+0x62) [0x7f4fd77a9942]
  [bt] (7) /home/ubuntu/miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7f51da4e59dd]
  [bt] (8) /home/ubuntu/miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7f51da4e5067]
```

Changing 10000000 to a smaller number works.

DGL is built on master branch, and the problem also exists in 0.7.1.

**Comment by BarclayII** [comment]
Probably it's not because of large number.  Loading the following file and execute `adj_product_graph` on CUDA 11.3 also throws a cuSPARSE internal error on the second `cusparseSpGEMM_workEstimation` call:

```
(bip, tg), _ = dgl.load_graphs('g.bin')
bip, tg = bip.to('cuda'), tg.to('cuda')
bng = dgl.adj_product_graph(tg, bip['fwd'], 'w')
```

File is [g.bin.gz](https://github.com/dmlc/dgl/files/7760646/g.bin.gz)

Stacktrace: 
```
DGLError                                  Traceback (most recent call last)
<ipython-input-21-f65eb3e0ee41> in <module>
----> 1 dgl.adj_product_graph(g.to('cuda'), bb.to('cuda'), 'w').edata['w']

~/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/transform.py in adj_product_graph(A, B, weight_name, etype)
   2640                 'For GPU graphs the number of nodes and edges must be less than 2 ** 31 - 1.')
   2641
-> 2642     C_gidx, C_weights = F.csrmm(
   2643         A._graph, A.edata[weight_name], B._graph, B.edata[weight_name], num_vtypes)
   2644     num_nodes_dict = {srctype: A.num_nodes(srctype), dsttype: B.num_nodes(dsttype)}

~/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/backend/pytorch/sparse.py in csrmm(gidxA, A_weights, gidxB, B_weights, num_vtypes)
    668 def csrmm(gidxA, A_weights, gidxB, B_weights, num_vtypes):
    669     nrows, ncols, C_indptr, C_indices, C_eids, C_weights = \
--> 670         CSRMM.apply(gidxA, A_weights, gidxB, B_weights, num_vtypes)
    671     gidxC = create_unitgraph_from_csr(
    672         num_vtypes, nrows.item(), ncols.item(), C_indptr, C_indices, C_eids,

~/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/backend/pytorch/sparse.py in forward(ctx, gidxA, A_weights, gidxB, B_weights, num_vtypes)
    555     @staticmethod
    556     def forward(ctx, gidxA, A_weights, gidxB, B_weights, num_vtypes):
--> 557         gidxC, C_weights = _csrmm(gidxA, A_weights, gidxB, B_weights, num_vtypes)
    558         nrows, ncols, C_indptr, C_indices, C_eids = gidxC.adjacency_matrix_tensors(0, False, 'csr')
    559         # Note: the returned C_indptr, C_indices and C_eids tensors MUST be the same

~/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/sparse.py in _csrmm(A, A_weights, B, B_weights, num_vtypes)
    648         The edge weights of the output graph.
    649     """
--> 650     C, C_weights = _CAPI_DGLCSRMM(
    651         A, F.to_dgl_nd(A_weights), B, F.to_dgl_nd(B_weights), num_vtypes)
    652     return C, F.from_dgl_nd(C_weights)

dgl/_ffi/_cython/./function.pxi in dgl._ffi._cy3.core.FunctionBase.__call__()

dgl/_ffi/_cython/./function.pxi in dgl._ffi._cy3.core.FuncCall()

dgl/_ffi/_cython/./base.pxi in dgl._ffi._cy3.core.CALL()

DGLError: [07:06:53] /mnt/b/gq/dgl/src/array/cuda/csr_mm.cu:87: Check failed: e == CUSPARSE_STATUS_SUCCESS: CUSPARSE ERROR: 7
Stack trace:
  [bt] (0) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(+0x6c9f02) [0x7f60929d7f02]
  [bt] (1) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(std::pair<dgl::aten::CSRMatrix, dgl::runtime::NDArray> dgl::aten::cusparse::CusparseSpgemm<float, int>(dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray)+0x63d) [0x7f60929d882d]
  [bt] (2) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(std::pair<dgl::aten::CSRMatrix, dgl::runtime::NDArray> dgl::aten::CSRMM<2, long, float>(dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::aten::CSRMatrix
const&, dgl::runtime::NDArray)+0xa68) [0x7f60929db768]
  [bt] (3) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::aten::CSRMM(dgl::aten::CSRMatrix, dgl::runtime::NDArray, dgl::aten::CSRMatrix, dgl::runtime::NDArray)+0x1197) [0x7f60927c3e47]
  [bt] (4) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(+0x4c161b) [0x7f60927cf61b]
  [bt] (5) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(+0x4c1e24) [0x7f60927cfe24]
  [bt] (6) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/libdgl.so(DGLFuncCall+0x62) [0x7f609280c292]
  [bt] (7) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so(+0x168f0) [0x7f606657f8f0]
  [bt] (8) /home/ubuntu/miniconda3/lib/python3.8/site-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so(+0x16d2b) [0x7f606657fd2b]
```

@nv-dlasalle @yaox12 Wonder if you were able to investigate (or find some other people to do so).

**Comment by BarclayII** [comment]
We temporarily worked around the issue by disabling CSRGEMM APIs in CUDA 11.0 and used the obsolete CSRGEMM CUDA 10.2 APIs.

**Comment by isratnisa** [comment]
From CUDA 11.0+, cuSPARSE’s SpSpMM operator does not support operations that involves more than 2**32-1 dense pairwise products. We worked around this in DGL by falling back to obsolete CUDA 10.2 interfaces (https://github.com/dmlc/dgl/pull/3635).
