### ISSUE TITLE
When using uva, CUDA error occur at tensor.to(device)

### ISSUE THREAD

**Issue by yinpeiqi** [dmlc/dgl#3917]
## 🐛 Bug
When try to perform inference using uva, several errors will occurred. I try the code for several times, and each time I got different result. 

## To Reproduce
```python
import dgl
import torch
import torch.nn.functional as F
import torch.nn as nn
import gc

import dgl
from dgl.nn import GATConv
from ogb.nodeproppred import DglNodePropPredDataset
from dgl.data import CiteseerGraphDataset, RedditDataset
from dgl.nn import GraphConv

class GAT(nn.Module):
    def __init__(self,
                 num_layers,
                 in_dim,
                 num_hidden,
                 num_classes,
                 heads,
                 activation,
                 feat_drop,
                 attn_drop,
                 negative_slope,
                 residual):
        super(GAT, self).__init__()
        self.num_layers = num_layers
        self.gat_layers = nn.ModuleList()
        self.activation = activation
        self.hidden_features = num_hidden
        self.heads = heads
        self.out_features = num_classes
        # input projection (no residual)
        self.gat_layers.append(GATConv(
            in_dim, num_hidden, heads[0],
            feat_drop, attn_drop, negative_slope, False, self.activation, allow_zero_in_degree=True))
        # hidden layers
        for l in range(1, num_layers - 1):
            # due to multi-head, the in_dim = num_hidden * num_heads
            self.gat_layers.append(GATConv(
                num_hidden * heads[l-1], num_hidden, heads[l],
                feat_drop, attn_drop, negative_slope, residual, self.activation, allow_zero_in_degree=True))
        # output projection
        self.gat_layers.append(GATConv(
            num_hidden * heads[-2], num_classes, heads[-1],
            feat_drop, attn_drop, negative_slope, residual, None, allow_zero_in_degree=True))

    def forward(self, g, inputs):
        h = inputs
        for l in range(self.num_layers - 1):
            h = self.gat_layers[l](g[l], h).flatten(1)
        # output projection
        logits = self.gat_layers[-1](g[-1], h).mean(1)
        return logits

    def forward_full(self, g, inputs):
        h = inputs
        for l in range(self.num_layers - 1):
            h = self.gat_layers[l](g, h).flatten(1)
        # output projection
        logits = self.gat_layers[-1](g, h).mean(1)
        return logits

    def inference(self, g, batch_size, device, x):
        torch.cuda.reset_peak_memory_stats()
        for l, layer in enumerate(self.gat_layers):
            gc.collect()
            torch.cuda.empty_cache()
            if l != self.num_layers - 1:
                y = torch.zeros(g.number_of_nodes(), self.heads[l] * self.hidden_features)
            else:
                y = torch.zeros(g.number_of_nodes(), self.out_features)
            g.ndata['feat'] = x
            sampler = dgl.dataloading.MultiLayerFullNeighborSampler(1, prefetch_node_feats=['feat'])
            dataloader = dgl.dataloading.NodeDataLoader(
                g, torch.arange(g.number_of_nodes()).to(device), sampler,
                batch_size=batch_size,
                shuffle=False,
                drop_last=False,
                use_uva=True,
                device=device,
                num_workers=0)
            for input_nodes, output_nodes, blocks in dataloader:
                torch.cuda.reset_peak_memory_stats()
                torch.cuda.empty_cache()
                block = blocks[0].to(device)
                h = block.srcdata['feat']
                h = h.to(device)

                h = layer(block, h)
                if l == self.num_layers - 1:
                    logits = h.mean(1)
                    y[output_nodes] = logits.cpu()
                else:
                    h = h.flatten(1)
                    y[output_nodes] = h.cpu()
        return y


def load_reddit():
    data = RedditDataset(self_loop=True)
    g = data[0]
    g.ndata['features'] = g.ndata['feat']
    return g, data.num_classes

if __name__ == '__main__':
    dataset = load_reddit()
    g : dgl.DGLHeteroGraph = dataset[0]
    train_mask = g.ndata['train_mask']
    val_mask = g.ndata['val_mask']
    test_mask = g.ndata['test_mask']
    feat = g.ndata['feat']
    labels = g.ndata['label']
    num_classes = dataset[1]
    in_feats = feat.shape[1]
    train_nid = torch.nonzero(train_mask, as_tuple=True)[0]
    hidden_feature = 128

    sampler = dgl.dataloading.MultiLayerNeighborSampler([10, 25, 50])
    dataloader = dgl.dataloading.NodeDataLoader(
        g, train_nid, sampler,
        batch_size=2000,
        shuffle=True,
        drop_last=False,
        num_workers=4)

    model = GAT(3, in_feats, hidden_feature, num_classes, [2, 2, 2], F.relu, 0.5, 0.5, 0.5, 0.5)

    device = "cuda:0"
    model = model.to(torch.device(device))
    opt = torch.optim.Adam(model.parameters())
    loss_fcn = nn.CrossEntropyLoss()

    for epoch in range(1):
        for input_nodes, output_nodes, blocks in dataloader:
            blocks = [b.to(torch.device(device)) for b in blocks]
            input_features = feat[input_nodes].to(torch.device(device))
            pred = model(blocks, input_features)
            output_labels = labels[output_nodes].to(torch.device(device))
            loss = loss_fcn(pred, output_labels)
            opt.zero_grad()
            loss.backward()
            opt.step()
            break

    with torch.no_grad():
        pred = model.inference(g, 10000, torch.device(device), feat)
        func_score = (torch.argmax(pred, dim=1) == labels).float().sum() / len(pred)

```

1.
1.
1.

Sometime I can run the code successfully, but sometime error will occur. This is the most common error I met, and it happened in h.cpu() or h.to(device). 
```
Traceback (most recent call last):
  File "/home/ec2-user/inference_helper/bug.py", line 146, in <module>
    pred = model.inference(g, 10000, torch.device(device), feat)
  File "/home/ec2-user/inference_helper/bug.py", line 95, in inference
    y[output_nodes] = h.cpu()
RuntimeError: CUDA error: invalid argument
```
Sometime this error may occur:
```
Traceback (most recent call last):
  File "/home/ec2-user/inference_helper/bug.py", line 146, in <module>
    pred = model.inference(g, 10000, torch.device(device), feat)
  File "/home/ec2-user/inference_helper/bug.py", line 89, in inference
    h = layer(block, h)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/nn/pytorch/conv/gatconv.py", line 282, in forward
    feat_src = feat_dst = self.fc(h_src).view(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (40736x602 and 256x256)
```
## Environment

 - DGL Version (e.g., 1.0): 0.9 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.10
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.9.4
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): Tesla V4
 - Any other relevant information: g4dn.8xlarge instance

**Comment by yaox12** [comment]
I think the second error is due to that you didn't update `g.ndata['feat']` for the second layer, right?

**Comment by yaox12** [comment]
Refer to this [example](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/multi_gpu_node_classification.py#L72) for using UVA for inference. You can simplify it to a single-GPU version by replacing `shared_tensor` with normal PyTorch tensors I think. It's considered an advanced usage as you may have to manually pin/unpin the feature columns.

**Comment by yinpeiqi** [comment]
@yaox12 Thanks for your reply. It seems the example is quite similar with my current code, I just create a new dataloader for each layer. I try to update `g.ndata['feat']`, and sometime it can execute the first layer correctly, while error occurred when **yield data from the second layer**:
```
Traceback (most recent call last):
  File "/home/ec2-user/inference_helper/bug.py", line 151, in <module>
    pred = model.inference(g, 10000, torch.device(device), feat)
  File "/home/ec2-user/inference_helper/bug.py", line 84, in inference
    for input_nodes, output_nodes, blocks in dataloader:
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 516, in __next__
    self._next_non_threaded() if not self.use_thread else self._next_threaded()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 496, in _next_non_threaded
    feats = _prefetch(batch, self.dataloader, stream)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 321, in _prefetch
    feats = recursive_apply(batch, _prefetch_for, dataloader)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/utils/internal.py", line 996, in recursive_apply
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/utils/internal.py", line 996, in <listcomp>
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/utils/internal.py", line 996, in recursive_apply
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/utils/internal.py", line 996, in <listcomp>
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/utils/internal.py", line 998, in recursive_apply
    return fn(data, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 291, in _prefetch_for
    return _prefetch_for_subgraph(item, dataloader)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 280, in _prefetch_for_subgraph
    _prefetch_update_feats(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 265, in _prefetch_update_feats
    feats[tid, key] = get_storage_func(parent_key, type_).fetch(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/frame.py", line 390, in fetch
    return super().fetch(indices, device, pin_memory=False, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/storages/pytorch_tensor.py", line 32, in fetch
    raise ValueError(
ValueError: Got indices on device cuda:0 whereas the feature tensor is on cpu. Please either (1) move the graph to GPU with to() method, or (2) pin the graph with pin_memory_() method.
```
So I try to unpin the graph after finished computing a layer. And most of the time the error I first reported will not occur(but may still happen). After this, It seems in my cases(I need to create a dataloader for each layer), I still need to move input data from CPU to pinned memory each time before calculation, and move output data from GPU to CPU memory each time after calculation. Is there any method to directly move output data from GPU to pinned memory, and remove the step moving input data from CPU from pinned memory?


Besides, when I try on large dataset (ogbn-papers100M, contains 1e9 nodes and 1e10 edges), a wired error occurred, I don't understand why the same code can't work for ogbn-papers100M, since it can work for ogbn-products, ogbn-arxiv and reddit.
```
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dgl-0.9-py3.9-linux-x86_64.egg/dgl/nn/pytorch/conv/gatconv.py", line 282, in forward
    feat_src = feat_dst = self.fc(h_src).view(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: resource already mapped
```

**Comment by yaox12** [comment]
> I try to update g.ndata['feat'], and sometime it can execute the first layer correctly, while error occurred when yield data from the second layer.

After updating `g.ndata['feat']`, it is no longer pinned. So you cannot use GPU indices to index it.

> Is there any method to directly move output data from GPU to pinned memory, and remove the step moving input data from CPU from pinned memory?

You can try inplace assignment, maybe something like
```python
y[:] = logits.cpu()
```

As for your case, I suggest you pop out all features attached to the graph, e.g., `g.ndata['feat']` and `g.ndata['features']`, set `prefetch_node_feats=None`, and manually slice the pinned feature tensor. For example:
```python
from dgl.utils import pin_memory_inplace, unpin_memory_inplace,gather_pinned_tensor_rows

y = g.ndata.pop('feat')
pin_memory_inplace(y)
....
# then in training iteration, input_nodes should be on GPU
h = gather_pinned_tensor_rows(y, input_nodes)
....
# update y
y[:] = logits.cpu()
...
# finally unpin the feature
unpin_memory_inplace(y)
```
Most of your errors are due to the incorrect pin/unpin/reuse pinned tensors.

**Comment by yaox12** [comment]
> when I try on large dataset (ogbn-papers100M, contains 1e9 nodes and 1e10 edges), a wired error occurred, I don't understand why the same code can't work for ogbn-papers100M, since it can work for ogbn-products, ogbn-arxiv and reddit.

I wonder if g4dn.8xlarge can host the whole ogbn-papers100M in CPU memory when instantiating all the sparse formats. I remember it takes more than 200 GB.

**Comment by yinpeiqi** [comment]
@yaox12 Thanks for your reply. I tried the solution you proposed, and I found that the `gather_pinned_tensor)rows` will not raise exception which occurred when I use `h[input_nodes].to(device)`. However, the `logits.cpu()` will still cause the problem I mentioned before: `RuntimeError: CUDA error: invalid argument`. My current inference code is like:
```python
    def inference(self, g, batch_size, device, x):
        for l, layer in enumerate(self.gat_layers):
            gc.collect()
            torch.cuda.empty_cache()
            if l != self.num_layers - 1:
                y = torch.zeros(g.number_of_nodes(), self.heads[l] * self.hidden_features)
            else:
                y = torch.zeros(g.number_of_nodes(), self.out_features)
            
            pin_memory_inplace(x)
            # pin_memory_inplace(y) # I also tried to pin y, but exception also raised

            sampler = dgl.dataloading.MultiLayerFullNeighborSampler(1)
            dataloader = dgl.dataloading.NodeDataLoader(
                g, torch.arange(g.number_of_nodes()).to(device), sampler,
                batch_size=batch_size,
                shuffle=False,
                drop_last=False,
                use_uva=True,
                device=device,
                num_workers=0)

            for input_nodes, output_nodes, blocks in dataloader:
                print(blocks)
                h = gather_pinned_tensor_rows(x, input_nodes)

                h = layer(blocks[0], h)
                if l == self.num_layers - 1:
                    h = h.mean(1)
                else:
                    h = h.flatten(1)

                tmp = h.to(y.device)
                y[output_nodes] = tmp

            unpin_memory_inplace(x)
            g.unpin_memory_()
            x = y
        return y
```
I found that this exception may raised when I call `to(device)`, maybe from CPU to GPU or from GPU to CPU. Since I cannot figure the reason for this exception, do we have any method to avoid or replace `to(device)`?

**Comment by yinpeiqi** [comment]
@yaox12 Thanks for your reply. Sometime this may also happen, error caused when transferring the output data from GPU to CPU.
```
Traceback (most recent call last):
  File "/home/ec2-user/inference_helper/bug.py", line 153, in <module>
    pred = model.inference(g, 10000, torch.device(device), feat)
  File "/home/ec2-user/inference_helper/bug.py", line 96, in inference
    tmp = h.to(y.device)
RuntimeError: CUDA error: invalid argument
```
Do you have any idea about how to debug for the error caused by `to(device)`? It seems we could not know anything from the asynchronous report.
