### ISSUE TITLE
[Benchmark] Many benchmark cases are failed within cuda initialization

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#5129]
## 🐛 Bug

Currently, all benchmark cases in `https://github.com/dmlc/dgl/tree/master/benchmarks` are crashed when start accessing GPU. 

## To Reproduce

1. pip install asv torchmetrics
2. cd benchmarks/
3. export DGL_BENCH_DEVICE=gpu
4. asv run -n -e --python=same --verbose --bench model_acc.bench_gat

## Expected behavior
The benchmarks should work; however, I got the following stack traces and error msg:
```
               Traceback (most recent call last):
                 File "/usr/local/lib/python3.8/dist-packages/asv/benchmark.py", line 1293, in main_run_server
                   main_run(run_args)
                 File "/usr/local/lib/python3.8/dist-packages/asv/benchmark.py", line 1167, in main_run
                   result = benchmark.do_run()
                 File "/usr/local/lib/python3.8/dist-packages/asv/benchmark.py", line 573, in do_run
                   return self.run(*self._current_params)
                 File "/usr/local/lib/python3.8/dist-packages/asv/benchmark.py", line 859, in run
                   return self.func(*param)
                 File "/opt/dgl/dgl-source/benchmarks/benchmarks/model_acc/bench_gat.py", line 97, in track_acc
                   g = data[0].to(device)
                 File "/usr/local/lib/python3.8/dist-packages/dgl/heterograph.py", line 5334, in to
                   ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
                 File "/usr/local/lib/python3.8/dist-packages/dgl/heterograph_index.py", line 256, in copy_to
                   return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
                 File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__
                 File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
                 File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
               dgl._ffi.base.DGLError: [18:42:59] /opt/dgl/dgl-source/src/runtime/cuda/cuda_device_api.cc:35: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: the operation cannot be performed in the present state
               Stack trace:
                 [bt] (0) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(+0x1641e18) [0x7f401d20fe18]
                 [bt] (1) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::AllocDataSpace(DGLContext, unsigned long, unsigned long, DGLDataType)+0x21d) [0x7f401d2138cd]
                 [bt] (2) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DGLDataType, DGLContext)+0x18a) [0x7f401d0680ba]
                 [bt] (3) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DGLContext const&) const+0xca) [0x7f401c93e82a]
                 [bt] (4) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0x1cc) [0x7f401d1d2b8c]
                 [bt] (5) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(dgl::HeteroGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0x112) [0x7f401d0b7922]
                 [bt] (6) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(+0x14fbf3c) [0x7f401d0c9f3c]
                 [bt] (7) /usr/local/lib/python3.8/dist-packages/dgl/libdgl.so(DGLFuncCall+0x69) [0x7f401d04cad9]
                 [bt] (8) /usr/local/lib/python3.8/dist-packages/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so(+0x1abad) [0x7f40e94a1bad]

```

## Environment

 - DGL Version (e.g., 1.0): 0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.13 and 1.14
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - CUDA/cuDNN version (if applicable): cuda12.0 
 - GPU models and configuration (e.g. V100): A5000 and V100

**Comment by chang-l** [comment]
I tried to root-cause this issue. It seems the crash happens at this commit: https://github.com/dmlc/dgl/commit/96297fb8fdd629fc2fd52872d718d78fa491cba1, i.e., under PyT 1.13, with the prev commit https://github.com/dmlc/dgl/commit/1d2291943e2b0f3862f202c1b123dbb15e0c76f3, a testing benchmark run can pass; while with the next commit https://github.com/dmlc/dgl/commit/96297fb8fdd629fc2fd52872d718d78fa491cba1,  I start observing the above crash.  

@yaox12  Can you please take a look see if you can reproduce?  Thanks.

**Comment by Rhett-Ying** [comment]
But it works well when trigger benchmark tests via `@dgl-bot run g4dn.12xlarge all dmlc/0.9.x`. see more details here: https://github.com/dmlc/dgl/pull/5124#issuecomment-1375259003

**Comment by chang-l** [comment]
@Rhett-Ying  If I understand it correctly, the triggered tasks are for [`dmlc/0.9.x`](https://github.com/dmlc/dgl/tree/0.9.x) branch, right? If so, I believe the commit https://github.com/dmlc/dgl/commit/96297fb8fdd629fc2fd52872d718d78fa491cba1 (Nov. 6) is not included in that release https://github.com/dmlc/dgl/commits/0.9.x.

**Comment by yaox12** [comment]
I can reproduce this issue. But it seems to appear with `asv` only. I tried calling `model_acc.bench_gat.track_acc` directly and it worked well.
```python
In [1]: from benchmarks.model_acc.bench_gat import track_acc

In [2]: track_acc("cora")
  NumNodes: 2708
  NumEdges: 10556
  NumFeats: 1433
  NumClasses: 7
  NumTrainingSamples: 140
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.
Out[2]: 81.8
```

**Comment by Rhett-Ying** [comment]
@chang-l  it's triggered both on the PR(in this case, it's `1.0.x`) and `0.9.x`.

**Comment by Rhett-Ying** [comment]
@yaox12 What I have tried and found is even run with `export DGL_BENCH_DEVICE=cpu;  asv run -n -e --python=same --verbose --bench model_acc.bench_gat`, it failed due to `cuda init error`. This is really weird. could you help confirm it?

**Comment by yaox12** [comment]
I almost locate it to the multi-processing with the `fork` start method in `asv`.
https://github.com/airspeed-velocity/asv/blob/e868fec325860d5d48a0625c716e05b6812cfc9b/asv/benchmark.py#L1157-L1173

1. I inserted a line `main_run(run_args)` before `pid = os.fork()`, and got correct results (but it would fail afterwards in the forked process).
```diff
            run_args = (benchmark_dir, benchmark_id, params_str, profile_path, result_file)
+++         main_run(run_args)
            pid = os.fork()
            if pid == 0:
```
2. I wrote a PyTorch-only "benchmark".
```python
import torch
import os

def _get_bench_device():
    device = os.environ.get("DGL_BENCH_DEVICE", "cpu")
    if device.lower() == "gpu":
        return "cuda:0"
    else:
        return device

def track_acc():
    device = _get_bench_device()

    a = torch.rand(10, device=device)
    b = torch.rand(10, device=device)

    return torch.sum(a * b).item()
```
It would fail with `export DGL_BENCH_DEVICE=gpu;  asv run -n -e --python=same --verbose --bench model_acc.bench_torch`. Error message is as follows. But it works with `export DGL_BENCH_DEVICE=cpu`.
```
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/asv/benchmark.py", line 1295, in main_run_server
main_run(run_args)
File "/opt/conda/lib/python3.8/site-packages/asv/benchmark.py", line 1167, in main_run
result = benchmark.do_run()
File "/opt/conda/lib/python3.8/site-packages/asv/benchmark.py", line 573, in do_run
return self.run(*self._current_params)
File "/opt/conda/lib/python3.8/site-packages/asv/benchmark.py", line 859, in run
return self.func(*param)
File "/workspace/dgl/benchmarks/benchmarks/model_acc/bench_torch.py", line 14, in track_acc
a = torch.rand(10, device=device)
File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 212, in _lazy_init
raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
asv: benchmark failed (exit status 1)
```

3. So regarding 

> @yaox12 What I have tried and found is even run with `export DGL_BENCH_DEVICE=cpu; asv run -n -e --python=same --verbose --bench model_acc.bench_gat`, it failed due to `cuda init error`. This is really weird. could you help confirm it?

We might have initialized the CUDA context somewhere, because `export CUDA_VISIBLE_DEVICES=-1; asv run -n -e --python=same --verbose --bench model_acc.bench_gat` runs successfully.

**Comment by yaox12** [comment]
**Update:**

This line of code https://github.com/dmlc/dgl/blob/c6228c01188d57db79c8f842eaf935e35587ff7b/python/dgl/backend/pytorch/sparse.py#L145
initializes the CUDA context when calling "import dgl".

**Comment by Rhett-Ying** [comment]
@yaox12 is it related to `fork`? how about trying with `--launch-method=spawn`? This is how we run when triggered with `@dgl-bot g4dn.12xlarge ....`.

**Comment by yaox12** [comment]
> @yaox12 is it related to `fork`? how about trying with `--launch-method=spawn`? This is how we run when triggered with `@dgl-bot g4dn.12xlarge ....`.

It works. So that's why the regression tests work well...

**Comment by chang-l** [comment]
I think it should be fixed...
