### ISSUE TITLE
DGL incompatible with V100 Cuda 11.7

### ISSUE THREAD

**Issue by universvm** [dmlc/dgl#5911]
## 🐛 Bug

Hi there,

I'm having problems setting up DGL with CUDA. 

In my setup I've got CUDA and torch running properly:

```
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.device_count())
print(torch.__version__)
```

Returns

```
11.7
8500
4
Tesla V100-PCIE-16GB
4
1.13.1+cu117
```
I am also able to run:

```
torch.tensor([0]).to('cuda:0')
>>> tensor([0], device='cuda:0')
```

## To Reproduce

I am not able to use conda so I installed DGL using pip in my poetry environment as described in your website:

```
poetry run pip install  dgl -f https://data.dgl.ai/wheels/cu117/repo.html
poetry run pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html
```

Everything seems to install correctly though unfortunately I get this CUDA error when running this simple example:

```
import dgl
import torch as th
u, v = th.tensor([0, 1, 2]), th.tensor([2, 3, 4])
g = dgl.graph((u, v))
g.ndata['x'] = th.randn(5, 3)  # original feature is on CPU
g.device
cuda_g = g.to('cuda:0')  # accepts any device objects from backend framework
cuda_g.device
cuda_g.ndata['x'].device       # feature data is copied to GPU too
# A graph constructed from GPU tensors is also on GPU
u, v = u.to('cuda:0'), v.to('cuda:0')
g = dgl.graph((u, v))
g.device

>>> DGLError: /opt/dgl/src/runtime/c_runtime_api.cc:82: Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl.

>>> Stack trace:
>>>  [bt] (0) /REDACTED/.venv/lib/python3.10/site-packages/dgl/libdgl.so(+0xf87d0) [0x7fabfe2f87d0]
>>>  [bt] (1) /REDACTED/.venv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::aten::Range(long, long, unsigned char, DGLContext)+0x107) [0x7fabfe2f89f7]
>>>  [bt] (2) /REDACTED/.venv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::UnitGraph::COO::Edges(unsigned long, std::string const&) const+0x9b) [0x7fabfe824e7b]
>>>  [bt] (3) /REDACTED/.venv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::UnitGraph::Edges(unsigned long, std::string const&) const+0xa1) [0x7fabfe81dfb1]
>>>  [bt] (4) /REDACTED/.venv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::HeteroGraph::Edges(unsigned long, std::string const&) const+0x2a) [0x7fabfe721d7a]
>>>  [bt] (5) /REDACTED/.venv/lib/python3.10/site-packages/dgl/libdgl.so(+0x52d931) [0x7fabfe72d931]
>>>  [bt] (6) /REDACTED/.venv/lib/python3.10/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7fabfe6b4fa8]
>>>  [bt] (7) /REDACTED/.venv/lib/python3.10/site-packages/dgl/_ffi/_cy3/core.cpython-310-x86_64-linux-gnu.so(+0x153f3) [0x7fabfce153f3]
>>>  [bt] (8) /REDACTED/.venv/lib/python3.10/site-packages/dgl/_ffi/_cy3/core.cpython-310-x86_64-linux-gnu.so(+0x15c0b) [0x7fabfce15c0b]
```

## Expected behavior

DGL running on GPU

## Environment

 - DGL Version (e.g., 1.0): 1.0.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.13
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): See above
 - Build command you used (if compiling from source):
 - Python version: 3.10
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100): V100
 - Any other relevant information:

## Additional context

A temporary workaround that I found is to install like this:

```
!poetry run  pip install dgl==1.0.1+cu117 -f https://data.dgl.ai/wheels/cu117/repo.html
```

**Comment by frozenbugs** [comment]
@yaox12 Hi Xin, can you take a look, thanks!

**Comment by yaox12** [comment]
It seems you didn't install the CUDA version of DGL somehow. Can you print the `dgl.__version__` to see the version info?

**Comment by universvm** [comment]
> It seems you didn't install the CUDA version of DGL somehow. Can you print the `dgl.__version__` to see the version info?

That seems the case, yes. But I used the command above which on your website says it should install the CUDA version of DGL.

> pip install  dgl -f https://data.dgl.ai/wheels/cu117/repo.html 

As per my post I had to explicitly specify it, as such:

> pip install dgl==1.0.1+cu117 -f https://data.dgl.ai/wheels/cu117/repo.html

**Comment by frozenbugs** [comment]
I tried `pip install dgl -f https://data.dgl.ai/wheels/cu117/repo.html`, it successfully installed 1.1.1+cu117.
```
Looking in links: https://data.dgl.ai/wheels/cu117/repo.html
Collecting dgl
  Downloading https://data.dgl.ai/wheels/cu117/dgl-1.1.1%2Bcu117-cp310-cp310-manylinux1_x86_64.whl (87.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (1.22.4)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (1.10.1)
Requirement already satisfied: networkx>=2.1 in /usr/local/lib/python3.10/dist-packages (from dgl) (3.1)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (2.27.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from dgl) (4.65.0)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (5.9.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (3.4)
Installing collected packages: dgl
Successfully installed dgl-1.1.1+cu117
DGL backend not selected or invalid.  Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
1.1.1+cu117
```

**Comment by universvm** [comment]
> I tried `pip install dgl -f https://data.dgl.ai/wheels/cu117/repo.html`, it successfully installed 1.1.1+cu117.
> 
> ```
> Looking in links: https://data.dgl.ai/wheels/cu117/repo.html
> Collecting dgl
>   Downloading https://data.dgl.ai/wheels/cu117/dgl-1.1.1%2Bcu117-cp310-cp310-manylinux1_x86_64.whl (87.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 MB 7.4 MB/s eta 0:00:00
> Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (1.22.4)
> Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (1.10.1)
> Requirement already satisfied: networkx>=2.1 in /usr/local/lib/python3.10/dist-packages (from dgl) (3.1)
> Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (2.27.1)
> Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from dgl) (4.65.0)
> Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.10/dist-packages (from dgl) (5.9.5)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (1.26.16)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (2023.5.7)
> Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (2.0.12)
> Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl) (3.4)
> Installing collected packages: dgl
> Successfully installed dgl-1.1.1+cu117
> DGL backend not selected or invalid.  Assuming PyTorch for now.
> Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
> 1.1.1+cu117
> ```

I wonder if this has to do with using a V100. Obviously I tried the same command and it did not work. 

It seems like I'm not alone:

- https://stackoverflow.com/questions/76519346/unable-to-install-dgl-cuany-version-in-google-colab/76568205#76568205
- https://discuss.dgl.ai/t/device-api-gpu-is-not-enabled/1112
- https://discuss.dgl.ai/t/dglerror-check-failed-allow-missing-device-api-cuda-is-not-enabled-please-install-the-cuda-version-of-dgl/3654/5

**Comment by BarclayII** [comment]
Could you try (1) the following pip command (maybe with poetry) and show us the complete log, and (2) run `python -c "import dgl; print(dgl); print(dgl.__version__)"` and show us the output?  I'd like to see if the package URL pip downloaded is correct.

**Comment by universvm** [comment]
No clue what happened but it seems to work now? 

From the forum discussions it seemed like a general problem with V100. Either way thanks again for you help!

**Comment by BarclayII** [comment]
Closing this issue.  Please feel free to reopen if the issue pops up again.
